import { ArrowRight, BarChart3, Check, House, ListTodo, MessageSquareText, ShieldCheck, TrendingUp, UsersRound } from "lucide-react";
import { getChatGPTUser } from "./chatgpt-auth";

export default async function LandingPage(){
  const user=await getChatGPTUser();
  const trialPath=user?"/onboarding":"/login?mode=signup";
  const loginPath=user?"/dashboard":"/login";
  return <main className="landing">
    <nav className="marketing-nav"><a className="marketing-brand" href="/"><span><House size={20}/></span>CloseKey</a><div><a href="#features">Features</a><a href="#pricing">Pricing</a><a className="login-link" href={loginPath} target="_top">{user?"Open CRM":"Log in"}</a><a className="nav-cta" href={trialPath} target="_top">Start free trial</a></div></nav>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">THE CRM BUILT FOR REAL ESTATE</p><h1>Turn more leads into <em>closed deals.</em></h1><p className="hero-text">CloseKey keeps every client, property, follow-up, conversation, and commission in one focused workspace.</p><div className="hero-actions"><a className="primary-cta" href={trialPath} target="_top">Start your 14-day free trial <ArrowRight size={18}/></a><a className="text-cta" href="#preview">See how it works</a></div><small><Check size={14}/> No credit card required <Check size={14}/> Set up in minutes</small></div><ProductPreview/></section>
    <section className="social-proof"><p>One clear system for the entire client journey</p><div><span><UsersRound/> Capture every lead</span><span><ListTodo/> Never miss a follow-up</span><span><TrendingUp/> See every deal</span><span><BarChart3/> Know your numbers</span></div></section>
    <section className="feature-section" id="features"><div className="section-copy"><p className="eyebrow">EVERYTHING IN ONE PLACE</p><h2>Your business moves fast.<br/>CloseKey keeps up.</h2><p>Spend less time rebuilding spreadsheets and searching through texts. Start every day knowing exactly who needs your attention.</p></div><div className="feature-grid"><Feature icon={UsersRound} title="Smart contact management" text="Keep buyer, seller, investor, property, and conversation details together."/><Feature icon={TrendingUp} title="Visual sales pipeline" text="Move opportunities from new lead to closing and forecast commission."/><Feature icon={ListTodo} title="Follow-up system" text="Turn every promise into a task so warm leads never go cold."/><Feature icon={MessageSquareText} title="Client communication" text="See messages and email activity alongside the deal they belong to."/></div></section>
    <section className="workflow" id="preview"><div className="workflow-card"><div><p className="eyebrow">YOUR DAILY COMMAND CENTER</p><h2>Know your next best move.</h2><p>CloseKey puts high-intent clients, overdue follow-ups, active offers, and revenue forecasts at the top of your day.</p><ul><li><Check/> Prioritized follow-up list</li><li><Check/> Deal-by-deal activity timeline</li><li><Check/> Live pipeline and commission forecast</li></ul></div><aside><div className="suggestion-icon"><TrendingUp/></div><small>SUGGESTED NEXT MOVE</small><h3>Follow up with Sofia while interest is high.</h3><p>She opened 3 Brickell listings in the last 24 hours.</p><button>Send a message <ArrowRight size={16}/></button></aside></div></section>
    <section className="pricing-section" id="pricing"><div><p className="eyebrow">SIMPLE PRICING</p><h2>One plan. Everything you need.</h2><p>Try the complete platform for 14 days. Add your payment method only when you’re ready to continue.</p></div><article className="price-card"><span>PRO</span><h3><strong>$49</strong> / month</h3><p>For independent agents building a repeatable business.</p><ul><li><Check/> Unlimited contacts and leads</li><li><Check/> Complete deal pipeline</li><li><Check/> Tasks and reminders</li><li><Check/> Messaging and email workspace</li><li><Check/> Invoices and reporting</li></ul><a href={trialPath} target="_top">Start 14-day free trial <ArrowRight size={17}/></a><small>No credit card required today</small></article></section>
    <section className="final-cta"><ShieldCheck/><h2>Your next closing starts with the right follow-up.</h2><p>Build a calmer, more organized real estate business with CloseKey.</p><a href={trialPath} target="_top">Start free for 14 days <ArrowRight size={18}/></a></section>
    <footer className="marketing-footer"><a className="marketing-brand" href="/"><span><House size={18}/></span>CloseKey</a><p>Real estate, organized.</p><span>© 2026 CloseKey CRM</span></footer>
  </main>
}

function Feature({icon:Icon,title,text}:{icon:typeof House;title:string;text:string}){return <article><span><Icon/></span><h3>{title}</h3><p>{text}</p></article>}
function ProductPreview(){const cards=[{name:"Icon Brickell #2804",client:"Sofia Martinez",value:"$795K"},{name:"Aventura Lakes",client:"Elena Rodriguez",value:"$975K"},{name:"SLS Lux #4102",client:"Marcus Chen",value:"$1.25M"}];return <div className="product-preview"><div className="preview-top"><span/><span/><span/></div><aside><b><House size={15}/></b>{[1,2,3,4,5].map(i=><i key={i}/>)}</aside><section><header><div><small>MONDAY, SEPTEMBER 14</small><h2>Good morning, Alex</h2></div><button>+ New opportunity</button></header><div className="preview-metrics"><div><small>PIPELINE VALUE</small><strong>$7.2M</strong></div><div><small>PROJECTED COMMISSION</small><strong>$181K</strong></div><div><small>NEW LEADS</small><strong>24</strong></div></div><div className="preview-pipeline"><h3>Deal pipeline</h3><div>{cards.map((c,i)=><article key={c.name}><small>{["NEW LEAD","QUALIFIED","SHOWING"][i]}</small><h4>{c.name}</h4><p>{c.client}</p><strong>{c.value}</strong></article>)}</div></div></section></div>}
